[package]
edition = "2021"
name = "blog_os"
version = "0.1.0"

[workspace]
members = ["kernel"]

[build-dependencies]
blog_os_kernel = {path = "kernel", artifact = "bin", target = "x86_64-unknown-none"}
bootloader = "0.11.0-alpha.0"
