[target.'cfg(target_os = "none")']
runner = "cargo run --package bootloader_helper --"

[alias]
kbuild = "build --package blog_os --target x86_64-blog_os.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
kimage = "run --package blog_os --target x86_64-blog_os.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -- --no-run"
krun = "run --package blog_os --target x86_64-blog_os.json -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
